const Ticket = require('./model');
const User = require('../../../models/User');

const TECH_ROLES = ['CRM Developer', 'CRM Consultant', 'System Architect'];
const ADMIN_ROLES = ['Super CRM Administrator'];
const FULL_ACCESS_ROLES = [...TECH_ROLES, ...ADMIN_ROLES, 'Executive User'];
const CAN_MANAGE_ROLES = [...TECH_ROLES, ...ADMIN_ROLES];
const AFFECTED_PAGES = ['Other','Dashboard','Leads','Lead Distribution','Sales Dashboard','Offers','Bookings','Campaigns','Analytics','Executive Dashboard','Teams','User Management','User Profile','Settings','CRM Dev Tools'];
const hasFullAccess = role => FULL_ACCESS_ROLES.includes(role);
const canManageTickets = role => CAN_MANAGE_ROLES.includes(role);
const populateTicket = query => query.populate('assignedTo','firstName lastName email role').populate('createdBy','firstName lastName email role').populate('comments.author','firstName lastName email role').populate('customer','name email');
const canCommentOnTicket = (user, ticket) => canManageTickets(user.role) || ticket.assignedTo?.toString() === user._id.toString() || ticket.createdBy?.toString() === user._id.toString();

exports.getTickets = async (req,res) => { try { const query = hasFullAccess(req.user.role) ? Ticket.find() : Ticket.find({createdBy:req.user._id}); const tickets = await populateTicket(query.sort({createdAt:-1})); res.status(200).json({success:true,count:tickets.length,data:tickets}); } catch(error){res.status(500).json({message:'Server Error',error:error.message});} };
exports.getTechnologyUsers = async (req,res) => { try { if(!canManageTickets(req.user.role)) return res.status(403).json({message:'Not authorized to view Technology users'}); const users=await User.find({role:{$in:TECH_ROLES},isActive:true}).select('firstName lastName email role isActive'); res.status(200).json({success:true,data:users}); } catch(error){res.status(500).json({message:'Server Error',error:error.message});} };
exports.getTicketById = async (req,res) => { try { const ticket=await Ticket.findById(req.params.id); if(!ticket)return res.status(404).json({message:'Ticket not found'}); if(!hasFullAccess(req.user.role)&&ticket.createdBy?.toString()!==req.user._id.toString())return res.status(403).json({message:'Not authorized to view this ticket'}); res.status(200).json({success:true,data:await populateTicket(ticket)}); } catch(error){res.status(500).json({message:'Server Error',error:error.message});} };
exports.createTicket = async (req,res) => { try { const {subject,description,priority,affectedPage,customer,assignedTo}=req.body; if(!subject?.trim()||!description?.trim())return res.status(400).json({message:'Subject and description are required'}); const canAssign=canManageTickets(req.user.role); const ticket=await Ticket.create({subject:subject.trim(),description:description.trim(),priority:canAssign?priority||'Medium':'Medium',affectedPage:AFFECTED_PAGES.includes(affectedPage)?affectedPage:'Other',customer:customer||null,requesterTeam:req.user.role,targetTeam:'Technology Team',assignedTo:canAssign?assignedTo||null:null,createdBy:req.user._id}); res.status(201).json({success:true,data:await populateTicket(ticket)}); } catch(error){res.status(400).json({message:'Failed to create ticket',error:error.message});} };
exports.addComment = async (req,res) => { try { const {text}=req.body; if(!text?.trim())return res.status(400).json({message:'Comment text is required'}); const ticket=await Ticket.findById(req.params.id); if(!ticket)return res.status(404).json({message:'Ticket not found'}); if(!canCommentOnTicket(req.user,ticket))return res.status(403).json({message:'Not authorized to comment on this ticket'}); ticket.comments.push({author:req.user._id,text:text.trim()}); await ticket.save(); res.status(201).json({success:true,data:await populateTicket(ticket)}); } catch(error){res.status(400).json({message:'Failed to add comment',error:error.message});} };
exports.updateTicket = async (req,res) => { try { let ticket=await Ticket.findById(req.params.id); if(!ticket)return res.status(404).json({message:'Ticket not found'}); const canManage=canManageTickets(req.user.role)||ticket.assignedTo?.toString()===req.user._id.toString(); const isCreator=ticket.createdBy?.toString()===req.user._id.toString(); if(!canManage&&!isCreator)return res.status(403).json({message:'Not authorized to edit this ticket'}); const updates={...req.body}; if(isCreator&&!canManage){const allowed={}; if(updates.description!==undefined)allowed.description=updates.description; if(updates.status==='Canceled')allowed.status='Canceled'; Object.assign(updates,allowed);} if(!canManageTickets(req.user.role)){delete updates.assignedTo; delete updates.priority;} if((updates.status==='Resolved'||updates.status==='Canceled')&&ticket.status!==updates.status)updates.resolvedAt=new Date(); ticket=await Ticket.findByIdAndUpdate(req.params.id,updates,{new:true,runValidators:true}); res.status(200).json({success:true,data:await populateTicket(ticket)}); } catch(error){res.status(500).json({message:'Server Error',error:error.message});} };
