const { SCOPES } = require('./permissionScopes');

const ALL_SCOPES = [SCOPES.SELF, SCOPES.TEAM, SCOPES.DEPARTMENT, SCOPES.BRANCH, SCOPES.COMPANY, SCOPES.GLOBAL];

const PERMISSIONS = [
  // ─── 1. IAM & SECURITY ──────────────────────────────────────────────────
  {
    permissionId: 'iam.users.view',
    displayName: 'View Users Directory',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'VIEW',
    description: 'Allows inspecting system users listing and basic profiles.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 101
  },
  {
    permissionId: 'iam.users.view_sensitive',
    displayName: 'View Sensitive Contact Details',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'VIEW',
    description: 'Allows inspecting personal phone numbers, emails, and address data.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 102
  },
  {
    permissionId: 'iam.users.create',
    displayName: 'Create User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'CREATE',
    description: 'Allows provisioning new system user credentials.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 103
  },
  {
    permissionId: 'iam.users.edit',
    displayName: 'Edit User Profile',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'EDIT',
    description: 'Allows modifying user title, department, shift, or supervisor.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 104
  },
  {
    permissionId: 'iam.users.deactivate',
    displayName: 'Deactivate User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows suspending active user access.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 105
  },
  {
    permissionId: 'iam.users.activate',
    displayName: 'Activate User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows restoring access to suspended user accounts.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 106
  },
  {
    permissionId: 'iam.users.lock',
    displayName: 'Lock User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows enforcing immediate security lockout on a user.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 107
  },
  {
    permissionId: 'iam.users.unlock',
    displayName: 'Unlock User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows unlocking locked user accounts.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 108
  },
  {
    permissionId: 'iam.users.reset_password',
    displayName: 'Reset User Password',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows triggering password reset link to user email.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 109
  },
  {
    permissionId: 'iam.users.force_password',
    displayName: 'Force Administrative Password Overwrite',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows instant manual password overwrite without email verification.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 110
  },
  {
    permissionId: 'iam.users.impersonate',
    displayName: 'Impersonate User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SUPER_ADMIN',
    description: 'Allows context-switching into arbitrary target user account.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 111
  },
  {
    permissionId: 'iam.users.assign_role',
    displayName: 'Assign Roles and Scopes',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows granting security roles and ABAC scope boundaries to users.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 112
  },
  {
    permissionId: 'iam.users.export',
    displayName: 'Export User Directory',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'EXPORT',
    description: 'Allows bulk exporting user records to CSV or Excel.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 113
  },
  {
    permissionId: 'iam.users.delete',
    displayName: 'Delete User Account',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'DELETE',
    description: 'Allows soft-deleting or archiving user records.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 114
  },
  {
    permissionId: 'iam.users.restore',
    displayName: 'Restore Archived User',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'RESTORE',
    description: 'Allows restoring deleted or archived user accounts.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 115
  },
  {
    permissionId: 'iam.users.clone',
    displayName: 'Clone User Permissions Profile',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'CREATE',
    description: 'Allows duplicating user role and permission profiles.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 116
  },
  {
    permissionId: 'iam.users.force_logout',
    displayName: 'Force Revoke Active User Sessions',
    category: 'USER_MANAGEMENT',
    module: 'IAM',
    submodule: 'Users Directory',
    action: 'SECURITY',
    description: 'Allows invalidating active JWT user login sessions.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 117
  },
  {
    permissionId: 'iam.roles.view',
    displayName: 'View Roles Directory',
    category: 'ROLES_MANAGEMENT',
    module: 'IAM',
    submodule: 'Roles Console',
    action: 'VIEW',
    description: 'Allows inspecting system security roles.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 118
  },
  {
    permissionId: 'iam.roles.create',
    displayName: 'Create Custom Enterprise Role',
    category: 'ROLES_MANAGEMENT',
    module: 'IAM',
    submodule: 'Roles Console',
    action: 'CREATE',
    description: 'Allows provisioning custom system roles.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 119
  },
  {
    permissionId: 'iam.roles.edit',
    displayName: 'Edit Role Metadata',
    category: 'ROLES_MANAGEMENT',
    module: 'IAM',
    submodule: 'Roles Console',
    action: 'EDIT',
    description: 'Allows editing role title and description.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 120
  },
  {
    permissionId: 'iam.roles.delete',
    displayName: 'Delete Custom Role',
    category: 'ROLES_MANAGEMENT',
    module: 'IAM',
    submodule: 'Roles Console',
    action: 'DELETE',
    description: 'Allows removing custom enterprise roles.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 121
  },
  {
    permissionId: 'iam.roles.duplicate',
    displayName: 'Duplicate Role Template',
    category: 'ROLES_MANAGEMENT',
    module: 'IAM',
    submodule: 'Roles Console',
    action: 'CREATE',
    description: 'Allows cloning existing role templates.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 122
  },
  {
    permissionId: 'iam.roles.manage_permissions',
    displayName: 'Manage Role Permissions Matrix',
    category: 'ROLES_MANAGEMENT',
    module: 'IAM',
    submodule: 'Roles Console',
    action: 'SECURITY',
    description: 'Allows adding or revoking permission claims from custom roles.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 123
  },
  {
    permissionId: 'iam.permissions.view_matrix',
    displayName: 'View Permission Matrix',
    category: 'PERMISSIONS_MATRIX',
    module: 'IAM',
    submodule: 'Permissions Console',
    action: 'VIEW',
    description: 'Allows inspecting master enterprise permission matrix.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 124
  },
  {
    permissionId: 'iam.permissions.edit_matrix',
    displayName: 'Edit Permission Matrix Definitions',
    category: 'PERMISSIONS_MATRIX',
    module: 'IAM',
    submodule: 'Permissions Console',
    action: 'SUPER_ADMIN',
    description: 'Allows configuring master permission definitions and scope limits.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 125
  },
  {
    permissionId: 'iam.audit.view',
    displayName: 'View Audit Logs',
    category: 'SECURITY_AUDIT',
    module: 'IAM',
    submodule: 'Audit Ledger',
    action: 'AUDIT',
    description: 'Allows inspecting security audit log entries.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 126
  },
  {
    permissionId: 'iam.audit.export',
    displayName: 'Export Audit Logs',
    category: 'SECURITY_AUDIT',
    module: 'IAM',
    submodule: 'Audit Ledger',
    action: 'EXPORT',
    description: 'Allows exporting audit trail records for compliance.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 127
  },
  {
    permissionId: 'iam.audit.delete',
    displayName: 'Delete Audit Logs',
    category: 'SECURITY_AUDIT',
    module: 'IAM',
    submodule: 'Audit Ledger',
    action: 'SUPER_ADMIN',
    description: 'Allows purging compliance audit history.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 128
  },

  // ─── 2. CRM & SALES ────────────────────────────────────────────────────
  {
    permissionId: 'crm.leads.view',
    displayName: 'View Leads Directory',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'VIEW',
    description: 'Allows viewing leads and opportunity pipelines.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 201
  },
  {
    permissionId: 'crm.leads.view_sensitive',
    displayName: 'View Sensitive Contact Info',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'VIEW',
    description: 'Allows unmasking lead direct phone numbers and emails.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 202
  },
  {
    permissionId: 'crm.leads.create',
    displayName: 'Create Lead',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'CREATE',
    description: 'Allows adding new leads to the pipeline.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 203
  },
  {
    permissionId: 'crm.leads.edit',
    displayName: 'Edit Lead Details',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'EDIT',
    description: 'Allows updating lead parameters and deal stages.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 204
  },
  {
    permissionId: 'crm.leads.delete',
    displayName: 'Delete Lead',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'DELETE',
    description: 'Allows removing lead records from database.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 205
  },
  {
    permissionId: 'crm.leads.restore',
    displayName: 'Restore Archived Lead',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'RESTORE',
    description: 'Allows restoring deleted lead records.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 206
  },
  {
    permissionId: 'crm.leads.assign',
    displayName: 'Assign Lead Agent',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'ASSIGN',
    description: 'Allows assigning leads to sales representatives.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 207
  },
  {
    permissionId: 'crm.leads.bulk_reassign',
    displayName: 'Bulk Reassign Leads',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'BULK_OPERATION',
    description: 'Allows batch transfer of lead ownership across representatives.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 208
  },
  {
    permissionId: 'crm.leads.bulk_delete',
    displayName: 'Bulk Delete Leads',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'BULK_OPERATION',
    description: 'Allows batch deletion of selected leads.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 209
  },
  {
    permissionId: 'crm.leads.bulk_update',
    displayName: 'Bulk Update Leads',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'BULK_OPERATION',
    description: 'Allows batch updating lead stages or tags.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 210
  },
  {
    permissionId: 'crm.leads.merge',
    displayName: 'Merge Duplicate Leads',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'EDIT',
    description: 'Allows merging duplicate lead records.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 211
  },
  {
    permissionId: 'crm.leads.archive',
    displayName: 'Archive Cold Lead',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'ARCHIVE',
    description: 'Allows archiving un-contacted or cold leads.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 212
  },
  {
    permissionId: 'crm.leads.convert',
    displayName: 'Convert Lead to Customer',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'EDIT',
    description: 'Allows converting won leads into active Customer accounts.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 213
  },
  {
    permissionId: 'crm.leads.export',
    displayName: 'Export Lead Database',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'EXPORT',
    description: 'Allows bulk downloading lead databases.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 214
  },
  {
    permissionId: 'crm.leads.import',
    displayName: 'Import Leads',
    category: 'LEADS_PIPELINE',
    module: 'CRM',
    submodule: 'Leads Workspace',
    action: 'IMPORT',
    description: 'Allows importing lead lists from CSV spreadsheets.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 215
  },
  {
    permissionId: 'crm.offers.view',
    displayName: 'View Quotations',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'VIEW',
    description: 'Allows inspecting offer quotations.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 216
  },
  {
    permissionId: 'crm.offers.create',
    displayName: 'Create Quotation',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'CREATE',
    description: 'Allows building new quotes for leads/customers.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 217
  },
  {
    permissionId: 'crm.offers.edit',
    displayName: 'Edit Quotation Items',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'EDIT',
    description: 'Allows modifying quote line items and base pricing.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 218
  },
  {
    permissionId: 'crm.offers.apply_standard_discount',
    displayName: 'Apply Standard Discount',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'FINANCIAL',
    description: 'Allows applying standard discount thresholds (e.g. <= 10%).',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 219
  },
  {
    permissionId: 'crm.offers.request_discount_override',
    displayName: 'Request High Discount Override',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'FINANCIAL',
    description: 'Allows submitting high-discount approval requests.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 220
  },
  {
    permissionId: 'crm.offers.approve_discount',
    displayName: 'Approve High Discount Override',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'APPROVE',
    description: 'Allows managerial sign-off on high-discount overrides.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 221
  },
  {
    permissionId: 'crm.offers.generate_pdf',
    displayName: 'Generate Quote PDF',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'EXPORT',
    description: 'Allows rendering quotation PDF documents.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 222
  },
  {
    permissionId: 'crm.offers.send_email',
    displayName: 'Send Quotation Email',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'EXPORT',
    description: 'Allows emailing quotation PDFs to customers.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 223
  },
  {
    permissionId: 'crm.offers.void',
    displayName: 'Void Quotation',
    category: 'QUOTATIONS',
    module: 'CRM',
    submodule: 'Quotation Builder',
    action: 'DELETE',
    description: 'Allows cancelling or voiding active quotes.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 224
  },
  {
    permissionId: 'crm.customers.view',
    displayName: 'View Customers Directory',
    category: 'CUSTOMERS',
    module: 'CRM',
    submodule: 'Customer Accounts',
    action: 'VIEW',
    description: 'Allows inspecting active customer directory.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 225
  },
  {
    permissionId: 'crm.customers.create',
    displayName: 'Create Customer Account',
    category: 'CUSTOMERS',
    module: 'CRM',
    submodule: 'Customer Accounts',
    action: 'CREATE',
    description: 'Allows adding new corporate or client customer accounts.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 226
  },
  {
    permissionId: 'crm.customers.edit',
    displayName: 'Edit Customer Profile',
    category: 'CUSTOMERS',
    module: 'CRM',
    submodule: 'Customer Accounts',
    action: 'EDIT',
    description: 'Allows updating customer company info or billing details.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 227
  },
  {
    permissionId: 'crm.customers.delete',
    displayName: 'Delete Customer Account',
    category: 'CUSTOMERS',
    module: 'CRM',
    submodule: 'Customer Accounts',
    action: 'DELETE',
    description: 'Allows removing customer account records.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 228
  },
  {
    permissionId: 'crm.customers.view_financials',
    displayName: 'View Customer Credit & Financials',
    category: 'CUSTOMERS',
    module: 'CRM',
    submodule: 'Customer Accounts',
    action: 'VIEW',
    description: 'Allows inspecting customer credit limits, invoices, and debt history.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 229
  },
  {
    permissionId: 'crm.customers.blacklist',
    displayName: 'Blacklist Customer Account',
    category: 'CUSTOMERS',
    module: 'CRM',
    submodule: 'Customer Accounts',
    action: 'EDIT',
    description: 'Allows placing customer accounts on credit hold or blacklist.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 230
  },

  // ─── 3. WMS & INVENTORY ────────────────────────────────────────────────
  {
    permissionId: 'wms.items.view',
    displayName: 'View Inventory Items Catalog',
    category: 'ITEMS_CATALOG',
    module: 'WMS',
    submodule: 'Items Catalog',
    action: 'VIEW',
    description: 'Allows inspecting inventory master item list and stock availability.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 301
  },
  {
    permissionId: 'wms.items.create',
    displayName: 'Define New SKU / Item',
    category: 'ITEMS_CATALOG',
    module: 'WMS',
    submodule: 'Items Catalog',
    action: 'CREATE',
    description: 'Allows defining new inventory items and SKUs.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 302
  },
  {
    permissionId: 'wms.items.edit',
    displayName: 'Edit SKU Parameters',
    category: 'ITEMS_CATALOG',
    module: 'WMS',
    submodule: 'Items Catalog',
    action: 'EDIT',
    description: 'Allows modifying SKU parameters, reorder points, and UOM.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 303
  },
  {
    permissionId: 'wms.items.set_reorder_point',
    displayName: 'Set Reorder Point & Safety Stock',
    category: 'ITEMS_CATALOG',
    module: 'WMS',
    submodule: 'Items Catalog',
    action: 'EDIT',
    description: 'Allows setting reorder alerts and safety stock levels.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 304
  },
  {
    permissionId: 'wms.items.delete',
    displayName: 'Delete SKU Record',
    category: 'ITEMS_CATALOG',
    module: 'WMS',
    submodule: 'Items Catalog',
    action: 'DELETE',
    description: 'Allows deleting SKU items from catalog.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 305
  },
  {
    permissionId: 'wms.receiving.view',
    displayName: 'View Inbound Receipts',
    category: 'RECEIVING',
    module: 'WMS',
    submodule: 'Inbound Receiving',
    action: 'VIEW',
    description: 'Allows viewing inbound PO receipts.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 306
  },
  {
    permissionId: 'wms.receiving.create_order',
    displayName: 'Create Receiving Order',
    category: 'RECEIVING',
    module: 'WMS',
    submodule: 'Inbound Receiving',
    action: 'CREATE',
    description: 'Allows creating inbound shipment receiving orders.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 307
  },
  {
    permissionId: 'wms.receiving.verify_goods',
    displayName: 'Verify Inbound Quantity & Quality',
    category: 'RECEIVING',
    module: 'WMS',
    submodule: 'Inbound Receiving',
    action: 'EDIT',
    description: 'Allows checking received physical items against PO lines.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 308
  },
  {
    permissionId: 'wms.receiving.post_receipt',
    displayName: 'Post Goods Receipt',
    category: 'RECEIVING',
    module: 'WMS',
    submodule: 'Inbound Receiving',
    action: 'FINANCIAL',
    description: 'Allows finalizing goods receipt (increases stock level in database).',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 309
  },
  {
    permissionId: 'wms.shipping.view',
    displayName: 'View Outbound Fulfillment',
    category: 'SHIPPING',
    module: 'WMS',
    submodule: 'Outbound Shipping',
    action: 'VIEW',
    description: 'Allows viewing outbound shipping queue.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 310
  },
  {
    permissionId: 'wms.shipping.create_wave',
    displayName: 'Release Wave Picking Tasks',
    category: 'SHIPPING',
    module: 'WMS',
    submodule: 'Outbound Shipping',
    action: 'CREATE',
    description: 'Allows generating wave pick tasks for warehouse operators.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 311
  },
  {
    permissionId: 'wms.shipping.assign_picker',
    displayName: 'Assign Pick Task Operator',
    category: 'SHIPPING',
    module: 'WMS',
    submodule: 'Outbound Shipping',
    action: 'ASSIGN',
    description: 'Allows assigning picking tasks to specific warehouse clerks.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 312
  },
  {
    permissionId: 'wms.shipping.print_label',
    displayName: 'Print Shipping & Courier Labels',
    category: 'SHIPPING',
    module: 'WMS',
    submodule: 'Outbound Shipping',
    action: 'EXPORT',
    description: 'Allows rendering packing slips and shipping labels.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 313
  },
  {
    permissionId: 'wms.shipping.post_issue',
    displayName: 'Post Goods Issue',
    category: 'SHIPPING',
    module: 'WMS',
    submodule: 'Outbound Shipping',
    action: 'FINANCIAL',
    description: 'Allows finalizing outbound shipment (decreases stock level in database).',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 314
  },
  {
    permissionId: 'wms.adjustments.view',
    displayName: 'View Inventory Adjustments',
    category: 'ADJUSTMENTS',
    module: 'WMS',
    submodule: 'Stock Adjustments',
    action: 'VIEW',
    description: 'Allows inspecting stock variance adjustment requests.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 315
  },
  {
    permissionId: 'wms.adjustments.create_request',
    displayName: 'Request Stock Adjustment',
    category: 'ADJUSTMENTS',
    module: 'WMS',
    submodule: 'Stock Adjustments',
    action: 'CREATE',
    description: 'Allows submitting stock quantity variance adjustment requests.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 316
  },
  {
    permissionId: 'wms.adjustments.approve',
    displayName: 'Approve Quantity Adjustment',
    category: 'ADJUSTMENTS',
    module: 'WMS',
    submodule: 'Stock Adjustments',
    action: 'APPROVE',
    description: 'Allows managerial sign-off on inventory adjustments (updates DB stock).',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 317
  },
  {
    permissionId: 'wms.adjustments.reject',
    displayName: 'Reject Quantity Adjustment',
    category: 'ADJUSTMENTS',
    module: 'WMS',
    submodule: 'Stock Adjustments',
    action: 'REJECT',
    description: 'Allows rejecting invalid inventory adjustment requests.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 318
  },
  {
    permissionId: 'wms.transfers.request',
    displayName: 'Request Stock Transfer',
    category: 'ADJUSTMENTS',
    module: 'WMS',
    submodule: 'Stock Transfers',
    action: 'CREATE',
    description: 'Allows creating inter-warehouse stock transfer requests.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 319
  },
  {
    permissionId: 'wms.transfers.execute',
    displayName: 'Execute Stock Transfer',
    category: 'ADJUSTMENTS',
    module: 'WMS',
    submodule: 'Stock Transfers',
    action: 'EDIT',
    description: 'Allows completing inter-warehouse stock transfer movements.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 320
  },
  {
    permissionId: 'wms.audits.cycle_count',
    displayName: 'Execute Cycle Count Audit',
    category: 'AUDITS',
    module: 'WMS',
    submodule: 'Cycle Counts',
    action: 'EDIT',
    description: 'Allows recording zone cycle count physical verifications.',
    defaultScope: SCOPES.BRANCH,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 321
  },
  {
    permissionId: 'wms.audits.physical_inventory',
    displayName: 'Execute Physical Inventory Audit',
    category: 'AUDITS',
    module: 'WMS',
    submodule: 'Physical Audits',
    action: 'SYSTEM',
    description: 'Allows freezing inventory movements for annual physical audit count.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 322
  },

  // ─── 4. SCM & PROCUREMENT ──────────────────────────────────────────────
  {
    permissionId: 'scm.procurement.view',
    displayName: 'View Requisitions & POs',
    category: 'PROCUREMENT',
    module: 'SCM',
    submodule: 'Purchase Orders',
    action: 'VIEW',
    description: 'Allows inspecting purchase requisitions and supplier POs.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 401
  },
  {
    permissionId: 'scm.procurement.create',
    displayName: 'Raise Purchase Order',
    category: 'PROCUREMENT',
    module: 'SCM',
    submodule: 'Purchase Orders',
    action: 'CREATE',
    description: 'Allows generating purchase orders to vendors.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 402
  },
  {
    permissionId: 'scm.procurement.approve_po',
    displayName: 'Approve High-Value Purchase Order',
    category: 'PROCUREMENT',
    module: 'SCM',
    submodule: 'Purchase Orders',
    action: 'APPROVE',
    description: 'Allows managerial sign-off on purchase orders exceeding $10,000.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 403
  },
  {
    permissionId: 'scm.vendors.view',
    displayName: 'View Vendors Directory',
    category: 'PROCUREMENT',
    module: 'SCM',
    submodule: 'Vendor Management',
    action: 'VIEW',
    description: 'Allows inspecting supplier contacts and lead times.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 404
  },
  {
    permissionId: 'scm.vendors.manage',
    displayName: 'Manage Vendors',
    category: 'PROCUREMENT',
    module: 'SCM',
    submodule: 'Vendor Management',
    action: 'EDIT',
    description: 'Allows creating or editing supplier records and contract terms.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 405
  },

  // ─── 5. CORE HRM & STAFF ───────────────────────────────────────────────
  {
    permissionId: 'hrm.staff.view_list',
    displayName: 'View Employee Directory',
    category: 'STAFF_ADMIN',
    module: 'HRM',
    submodule: 'Personal Directory',
    action: 'VIEW',
    description: 'Allows inspecting staff directory and organizational structure.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 501
  },
  {
    permissionId: 'hrm.staff.view_sensitive',
    displayName: 'View Sensitive Identity Docs',
    category: 'STAFF_ADMIN',
    module: 'HRM',
    submodule: 'Personal Directory',
    action: 'VIEW',
    description: 'Allows viewing employee national ID, passport, or degree files.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 502
  },
  {
    permissionId: 'hrm.staff.create',
    displayName: 'Register Employee Master Record',
    category: 'STAFF_ADMIN',
    module: 'HRM',
    submodule: 'Personal Directory',
    action: 'CREATE',
    description: 'Allows onboarding new employee master files.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 503
  },
  {
    permissionId: 'hrm.staff.edit_profile',
    displayName: 'Edit Employee Profile',
    category: 'STAFF_ADMIN',
    module: 'HRM',
    submodule: 'Personal Directory',
    action: 'EDIT',
    description: 'Allows updating staff title, department, or shift assignment.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 504
  },
  {
    permissionId: 'hrm.staff.delete',
    displayName: 'Terminate & Archive Employee',
    category: 'STAFF_ADMIN',
    module: 'HRM',
    submodule: 'Personal Directory',
    action: 'DELETE',
    description: 'Allows initiating offboarding termination on staff records.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 505
  },
  {
    permissionId: 'hrm.staff.restore',
    displayName: 'Restore Terminated Employee',
    category: 'STAFF_ADMIN',
    module: 'HRM',
    submodule: 'Personal Directory',
    action: 'RESTORE',
    description: 'Allows re-instating terminated staff records.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 506
  },
  {
    permissionId: 'hrm.contracts.view_base_salary',
    displayName: 'View Basic Salary Figures',
    category: 'COMPENSATION',
    module: 'HRM',
    submodule: 'Contracts & Salary',
    action: 'HR',
    description: 'Allows inspecting employee basic salary amounts.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 507
  },
  {
    permissionId: 'hrm.contracts.view_net_salary',
    displayName: 'View Net Salary Payout',
    category: 'COMPENSATION',
    module: 'HRM',
    submodule: 'Contracts & Salary',
    action: 'HR',
    description: 'Allows inspecting final calculated net pay after deductions.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 508
  },
  {
    permissionId: 'hrm.contracts.edit_salary_components',
    displayName: 'Edit Salary Components',
    category: 'COMPENSATION',
    module: 'HRM',
    submodule: 'Contracts & Salary',
    action: 'HR',
    description: 'Allows adding or modifying salary allowances and tax rates.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 509
  },
  {
    permissionId: 'hrm.contracts.edit_net_salary',
    displayName: 'Direct Override of Net Salary',
    category: 'COMPENSATION',
    module: 'HRM',
    submodule: 'Contracts & Salary',
    action: 'HR',
    description: 'Allows manual net salary adjustment overrides.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 510
  },
  {
    permissionId: 'hrm.contracts.upload_signed_pdf',
    displayName: 'Upload Signed Contract PDF',
    category: 'COMPLIANCE',
    module: 'HRM',
    submodule: 'Compliance Documents',
    action: 'UPLOAD',
    description: 'Allows uploading employee signed contract PDF files.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 511
  },
  {
    permissionId: 'hrm.contracts.verify_doc',
    displayName: 'Verify Government Compliance Document',
    category: 'COMPLIANCE',
    module: 'HRM',
    submodule: 'Compliance Documents',
    action: 'APPROVE',
    description: 'Allows approving employee national ID, military, or degree uploads.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 512
  },
  {
    permissionId: 'hrm.leaves.apply',
    displayName: 'Submit Leave Request',
    category: 'LEAVE_MGMT',
    module: 'HRM',
    submodule: 'Leave Management',
    action: 'CREATE',
    description: 'Allows submitting vacation or sick leave requests.',
    defaultScope: SCOPES.SELF,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 513
  },
  {
    permissionId: 'hrm.leaves.approve',
    displayName: 'Approve Leave Request',
    category: 'LEAVE_MGMT',
    module: 'HRM',
    submodule: 'Leave Management',
    action: 'APPROVE',
    description: 'Allows managerial sign-off on employee leave applications.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 514
  },
  {
    permissionId: 'hrm.leaves.reject',
    displayName: 'Reject Leave Request',
    category: 'LEAVE_MGMT',
    module: 'HRM',
    submodule: 'Leave Management',
    action: 'REJECT',
    description: 'Allows declining employee leave requests.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 515
  },

  // ─── 6. ATTENDANCE & RTM ───────────────────────────────────────────────
  {
    permissionId: 'attendance.rtm.view_live',
    displayName: 'View Live RTM Dashboard',
    category: 'RTM_MONITORING',
    module: 'ATTENDANCE',
    submodule: 'Real-Time Monitor',
    action: 'VIEW',
    description: 'Allows inspecting live agent AUX status dashboard.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 601
  },
  {
    permissionId: 'attendance.rtm.override_aux',
    displayName: 'Override Agent AUX Status',
    category: 'RTM_MONITORING',
    module: 'ATTENDANCE',
    submodule: 'Real-Time Monitor',
    action: 'EDIT',
    description: 'Allows changing an agent current AUX status manually.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 602
  },
  {
    permissionId: 'attendance.schedules.view',
    displayName: 'View Work Shift Rosters',
    category: 'ROSTERS',
    module: 'ATTENDANCE',
    submodule: 'Shift Schedules',
    action: 'VIEW',
    description: 'Allows inspecting team work shift calendars.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 603
  },
  {
    permissionId: 'attendance.schedules.manage',
    displayName: 'Manage Shift Rosters',
    category: 'ROSTERS',
    module: 'ATTENDANCE',
    submodule: 'Shift Schedules',
    action: 'EDIT',
    description: 'Allows configuring and assigning monthly work shift rosters.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 604
  },

  // ─── 7. PAYROLL & FINANCE ──────────────────────────────────────────────
  {
    permissionId: 'payroll.engine.view_runs',
    displayName: 'View Monthly Payroll Runs',
    category: 'PAYROLL_EXECUTION',
    module: 'PAYROLL',
    submodule: 'Payroll Engine',
    action: 'VIEW',
    description: 'Allows viewing historical and active monthly payroll calculations.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 701
  },
  {
    permissionId: 'payroll.engine.calculate',
    displayName: 'Initiate Payroll Run Engine',
    category: 'PAYROLL_EXECUTION',
    module: 'PAYROLL',
    submodule: 'Payroll Engine',
    action: 'FINANCIAL',
    description: 'Allows running monthly gross-to-net payroll engine.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 702
  },
  {
    permissionId: 'payroll.engine.approve_run',
    displayName: 'Approve Monthly Payroll Run',
    category: 'PAYROLL_EXECUTION',
    module: 'PAYROLL',
    submodule: 'Payroll Engine',
    action: 'APPROVE',
    description: 'Allows formal managerial sign-off and locking of payroll run.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 703
  },
  {
    permissionId: 'payroll.engine.reject_run',
    displayName: 'Reject Payroll Run',
    category: 'PAYROLL_EXECUTION',
    module: 'PAYROLL',
    submodule: 'Payroll Engine',
    action: 'REJECT',
    description: 'Allows declining payroll calculations for recalculation.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 704
  },
  {
    permissionId: 'payroll.engine.release_disbursement',
    displayName: 'Release Bank Fund Disbursement',
    category: 'PAYROLL_EXECUTION',
    module: 'PAYROLL',
    submodule: 'Payroll Engine',
    action: 'FINANCIAL',
    description: 'Allows dispatching direct payment orders to company bank/gateways.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 705
  },
  {
    permissionId: 'payroll.engine.reverse',
    displayName: 'Reverse Processed Payroll Run',
    category: 'PAYROLL_EXECUTION',
    module: 'PAYROLL',
    submodule: 'Payroll Engine',
    action: 'FINANCIAL',
    description: 'Allows rolling back executed payroll runs.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 706
  },
  {
    permissionId: 'payroll.banking.view_company',
    displayName: 'View Company Source Bank Accounts',
    category: 'BANKING',
    module: 'PAYROLL',
    submodule: 'Company Bank Accounts',
    action: 'VIEW',
    description: 'Allows inspecting corporate treasury funding accounts.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 707
  },
  {
    permissionId: 'payroll.banking.verify_employee',
    displayName: 'Verify Staff Bank Payout Account',
    category: 'BANKING',
    module: 'PAYROLL',
    submodule: 'Staff Payout Accounts',
    action: 'APPROVE',
    description: 'Allows approving employee Destination Payout Bank IBANs.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 708
  },
  {
    permissionId: 'payroll.banking.manage_company',
    displayName: 'Manage Corporate Treasury Accounts',
    category: 'BANKING',
    module: 'PAYROLL',
    submodule: 'Company Bank Accounts',
    action: 'FINANCIAL',
    description: 'Allows adding/editing corporate source funding bank accounts.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 709
  },
  {
    permissionId: 'payroll.loans.apply',
    displayName: 'Apply for Employee Loan',
    category: 'STAFF_LOANS',
    module: 'PAYROLL',
    submodule: 'Staff Loans',
    action: 'CREATE',
    description: 'Allows submitting salary advance or loan requests.',
    defaultScope: SCOPES.SELF,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 710
  },
  {
    permissionId: 'payroll.loans.approve',
    displayName: 'Approve Employee Loan',
    category: 'STAFF_LOANS',
    module: 'PAYROLL',
    submodule: 'Staff Loans',
    action: 'APPROVE',
    description: 'Allows managerial sign-off on staff loan applications.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 711
  },

  // ─── 8. TALENT & ATS ───────────────────────────────────────────────────
  {
    permissionId: 'talent.ats.view_vacancies',
    displayName: 'View Job Postings',
    category: 'RECRUITMENT',
    module: 'TALENT',
    submodule: 'Recruitment ATS',
    action: 'VIEW',
    description: 'Allows inspecting open job postings and applicants.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 801
  },
  {
    permissionId: 'talent.ats.create_vacancy',
    displayName: 'Create Job Posting',
    category: 'RECRUITMENT',
    module: 'TALENT',
    submodule: 'Recruitment ATS',
    action: 'CREATE',
    description: 'Allows creating new job vacancy requisitions.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 802
  },
  {
    permissionId: 'talent.ats.add_feedback',
    displayName: 'Submit Interview Scorecards',
    category: 'RECRUITMENT',
    module: 'TALENT',
    submodule: 'Recruitment ATS',
    action: 'EDIT',
    description: 'Allows logging candidate interview evaluations and ratings.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 803
  },

  // ─── 9. TICKETS & CS ───────────────────────────────────────────────────
  {
    permissionId: 'tickets.desk.view',
    displayName: 'View Customer Support Tickets',
    category: 'SERVICE_DESK',
    module: 'TICKETS',
    submodule: 'Service Desk',
    action: 'VIEW',
    description: 'Allows inspecting support ticket queues.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 901
  },
  {
    permissionId: 'tickets.desk.create',
    displayName: 'Create Support Ticket',
    category: 'SERVICE_DESK',
    module: 'TICKETS',
    submodule: 'Service Desk',
    action: 'CREATE',
    description: 'Allows logging new customer support tickets.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 902
  },
  {
    permissionId: 'tickets.desk.edit',
    displayName: 'Edit & Update Ticket',
    category: 'SERVICE_DESK',
    module: 'TICKETS',
    submodule: 'Service Desk',
    action: 'EDIT',
    description: 'Allows updating ticket status, priority, and resolution notes.',
    defaultScope: SCOPES.TEAM,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 903
  },

  // ─── 10. MARKETING ─────────────────────────────────────────────────────
  {
    permissionId: 'marketing.campaigns.view',
    displayName: 'View Marketing Campaigns',
    category: 'CAMPAIGNS',
    module: 'MARKETING',
    submodule: 'Campaigns Hub',
    action: 'VIEW',
    description: 'Allows inspecting marketing campaign ROI statistics.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 1001
  },
  {
    permissionId: 'marketing.campaigns.create',
    displayName: 'Create Marketing Campaign',
    category: 'CAMPAIGNS',
    module: 'MARKETING',
    submodule: 'Campaigns Hub',
    action: 'CREATE',
    description: 'Allows launching new omnichannel marketing campaigns.',
    defaultScope: SCOPES.DEPARTMENT,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'MEDIUM',
    isDangerous: false,
    requiresAudit: true,
    displayOrder: 1002
  },

  // ─── 11. ADMIN & CONFIG ────────────────────────────────────────────────
  {
    permissionId: 'admin.settings.view',
    displayName: 'View Global Settings',
    category: 'GLOBAL_CONFIG',
    module: 'ADMIN',
    submodule: 'System Settings',
    action: 'VIEW',
    description: 'Allows inspecting global ERP configuration.',
    defaultScope: SCOPES.COMPANY,
    allowedScopes: ALL_SCOPES,
    riskLevel: 'LOW',
    isDangerous: false,
    requiresAudit: false,
    displayOrder: 1101
  },
  {
    permissionId: 'admin.settings.update_business_model',
    displayName: 'Toggle System Business Model',
    category: 'GLOBAL_CONFIG',
    module: 'ADMIN',
    submodule: 'System Settings',
    action: 'CONFIGURATION',
    description: 'Allows toggling ERP mode between Service, Product, and Both.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 1102
  },
  {
    permissionId: 'admin.settings.update_smtp',
    displayName: 'Update System SMTP Server',
    category: 'GLOBAL_CONFIG',
    module: 'ADMIN',
    submodule: 'System Settings',
    action: 'CONFIGURATION',
    description: 'Allows modifying corporate email outbound server settings.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'HIGH',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 1103
  },
  {
    permissionId: 'admin.settings.manage_gateways',
    displayName: 'Manage Payment Gateway Credentials',
    category: 'GLOBAL_CONFIG',
    module: 'ADMIN',
    submodule: 'System Settings',
    action: 'SUPER_ADMIN',
    description: 'Allows modifying Fawry, PayMob, and InstaPay API credentials.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 1104
  },
  {
    permissionId: 'admin.devtools.seed_database',
    displayName: 'Execute Database Maintenance & Seeding',
    category: 'DEVTOOLS',
    module: 'ADMIN',
    submodule: 'Developer Tools',
    action: 'SUPER_ADMIN',
    description: 'Allows running diagnostic database seeds and index maintenance.',
    defaultScope: SCOPES.GLOBAL,
    allowedScopes: [SCOPES.GLOBAL],
    riskLevel: 'CRITICAL',
    isDangerous: true,
    requiresAudit: true,
    displayOrder: 1105
  }
];

module.exports = {
  PERMISSIONS
};
