apiVersion: v1
kind: ConfigMap
metadata:
  name: erp-backend-config
  namespace: {{ .Values.global.namespace }}
data:
  PORT: "5000"
  NODE_ENV: {{ .Values.global.environment | quote }}
  CLIENT_URL: "http://core360.example.com"
  ENABLE_CRON_JOBS: "true"
  SHUTDOWN_TIMEOUT_MS: "10000"
