apiVersion: v1
kind: Secret
metadata:
  name: erp-backend-secrets
  namespace: super-erp
type: Opaque
stringData:
  MONGODB_URI: "mongodb://mongo-service:27017/super-erp"
  JWT_SECRET: "your_production_high_entropy_jwt_secret_key"
  ENCRYPTION_SECRET: "your_production_aes_256_encryption_secret"
  META_VERIFY_TOKEN: "your_meta_webhook_verify_token"
