const express = require('express');
const router = express.Router();
const { protect } = require('../../middleware/auth');
const { checkPermission } = require('../../middleware/authorize');
const { getWarehouses, createWarehouse, updateWarehouse, getLots, getSerials } = require('../../controllers/inventoryController');
const itemRoutes = require('./items/routes');
const receivingRoutes = require('./receiving/routes');
const shippingRoutes = require('./shipping/routes');
const transferRoutes = require('./transfers/routes');
const adjustmentRoutes = require('./adjustments/routes');
const auditRoutes = require('./audits/routes');
const intelligenceRoutes = require('./intelligence/routes');
router.use(protect);
router.use(itemRoutes);
router.use(receivingRoutes);
router.use(shippingRoutes);
router.use('/transfers', transferRoutes);
router.use('/adjustments', adjustmentRoutes);
router.use('/audits', auditRoutes);
router.use(intelligenceRoutes);
router.get('/warehouses', checkPermission('wms.items.view'), getWarehouses);
router.post('/warehouses', checkPermission('wms.items.create'), createWarehouse);
router.put('/warehouses/:id', checkPermission('wms.items.edit'), updateWarehouse);
router.get('/lots', checkPermission('wms.items.view'), getLots);
router.get('/serials', checkPermission('wms.items.view'), getSerials);
module.exports = router;
