const express = require('express');
const router = express.Router();
const controller = require('./controller');
const { applyDiscount } = require('../../../controllers/settingsController');
const { protect } = require('../../../middleware/auth');
const { checkPermission } = require('../../../middleware/authorize');
const upload = require('../../../middleware/upload');
const uploadAttachment = require('../../../middleware/uploadAttachment');

router.get('/lead/:leadId', protect, checkPermission('crm.offers.view'), controller.getOffersByLead);
router.get('/locator/:recordLocator', protect, checkPermission('crm.offers.view'), controller.getOfferByLocator);
router.get('/:id', protect, checkPermission('crm.offers.view'), controller.getOfferById);
router.post('/', protect, checkPermission('crm.offers.create'), controller.createOffer);
router.put('/:id', protect, checkPermission('crm.offers.edit'), controller.updateOffer);
router.delete('/:id', protect, checkPermission('crm.offers.void'), controller.deleteOffer);
router.post('/:id/send', protect, uploadAttachment.array('attachments'), checkPermission('crm.offers.send_email'), controller.sendOffer);
router.post('/:id/images', protect, upload.single('image'), checkPermission('crm.offers.edit'), controller.uploadOfferImage);
router.delete('/:id/images/:imageId', protect, checkPermission('crm.offers.edit'), controller.deleteOfferImage);
router.get('/:id/communications', protect, checkPermission('crm.offers.view'), controller.getOfferCommunicationLog);
router.post('/:id/communications/reply', protect, checkPermission('crm.offers.edit'), controller.addOfferCommunicationReply);
router.post('/:id/call', protect, checkPermission('crm.offers.edit'), controller.initiateAvayaCall);
router.post('/:id/discount', protect, checkPermission('crm.offers.apply_standard_discount'), applyDiscount);
router.get('/templates', protect, checkPermission('crm.offers.view'), controller.getTemplates);
router.post('/templates', protect, checkPermission('crm.offers.create'), controller.createTemplate);
router.put('/templates/:id', protect, checkPermission('crm.offers.edit'), controller.updateTemplate);
router.delete('/templates/:id', protect, checkPermission('crm.offers.void'), controller.deleteTemplate);
module.exports = router;
