import { useEffect, useState } from 'react';
import API from '../../services/api';

export default function HrmExtensionsPage() {
  const [tab, setTab] = useState('contracts');
  const [contracts, setContracts] = useState([]);
  const [accounts, setAccounts] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [contract, setContract] = useState({ employeeId:'', contractNumber:'', startDate:'', endDate:'', basicSalary:0, status:'Active' });
  const [bank, setBank] = useState({ employeeId:'', bankName:'', accountNumber:'', iban:'', accountHolderName:'', currency:'EGP', status:'Active' });
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); try { const [c,b,e] = await Promise.all([API.get('/hrm/contracts'), API.get('/hrm/banking/accounts'), API.get('/hrm/employees')]); setContracts(c.data.data||[]); setAccounts(b.data.data||[]); setEmployees(e.data.data||[]); } catch(e){ setError(e.response?.data?.message||'Failed to load HRM extensions'); } finally { setLoading(false); } };
  useEffect(()=>{load();},[]);
  const save = async (path, body, reset) => { setSaving(true); setError(''); try { await API.post(path,body); reset(); await load(); } catch(e){ setError(e.response?.data?.message||'Save failed'); } finally { setSaving(false); } };
  if(loading) return <div className="loading-state">Loading HRM extensions…</div>;
  return <div className="page-container"><div className="page-header"><div><h1>HRM Extensions</h1><p>Contracts and employee banking integrated with the HRM backend.</p></div></div>{error&&<div className="alert alert-error">{error}</div>}<div className="tabs" style={{display:'flex',gap:8,margin:'20px 0'}}><button onClick={()=>setTab('contracts')} className={tab==='contracts'?'active':''}>Contracts</button><button onClick={()=>setTab('banking')} className={tab==='banking'?'active':''}>Employee Banking</button></div>
  {tab==='contracts'&&<section className="card"><h2>Employee Contracts</h2><form onSubmit={e=>{e.preventDefault();save('/hrm/contracts',contract,()=>setContract({ employeeId:'',contractNumber:'',startDate:'',endDate:'',basicSalary:0,status:'Active' }));}} style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><select value={contract.employeeId} onChange={e=>setContract({...contract,employeeId:e.target.value})} required><option value="">Select employee</option>{employees.map(x=><option key={x._id} value={x._id}>{x.name||x.fullName||x.employeeNumber}</option>)}</select><input placeholder="Contract number" value={contract.contractNumber} onChange={e=>setContract({...contract,contractNumber:e.target.value})} required/><input type="date" value={contract.startDate} onChange={e=>setContract({...contract,startDate:e.target.value})} required/><input type="date" value={contract.endDate} onChange={e=>setContract({...contract,endDate:e.target.value})}/><input type="number" min="0" placeholder="Basic salary" value={contract.basicSalary} onChange={e=>setContract({...contract,basicSalary:e.target.value})}/><button disabled={saving}>Create contract</button></form><table><thead><tr><th>Contract</th><th>Employee</th><th>Start</th><th>Salary</th><th>Status</th></tr></thead><tbody>{contracts.map(x=><tr key={x._id}><td>{x.contractNumber}</td><td>{x.employee?.name||x.employeeId}</td><td>{x.startDate?.slice(0,10)}</td><td>{x.basicSalary}</td><td>{x.status}</td></tr>)}</tbody></table></section>}
  {tab==='banking'&&<section className="card"><h2>Employee Bank Accounts</h2><form onSubmit={e=>{e.preventDefault();save('/hrm/banking/accounts',bank,()=>setBank({ employeeId:'',bankName:'',accountNumber:'',iban:'',accountHolderName:'',currency:'EGP',status:'Active' }));}} style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><select value={bank.employeeId} onChange={e=>setBank({...bank,employeeId:e.target.value})} required><option value="">Select employee</option>{employees.map(x=><option key={x._id} value={x._id}>{x.name||x.fullName||x.employeeNumber}</option>)}</select><input placeholder="Bank name" value={bank.bankName} onChange={e=>setBank({...bank,bankName:e.target.value})} required/><input placeholder="Account number" value={bank.accountNumber} onChange={e=>setBank({...bank,accountNumber:e.target.value})} required/><input placeholder="IBAN" value={bank.iban} onChange={e=>setBank({...bank,iban:e.target.value})}/><input placeholder="Account holder" value={bank.accountHolderName} onChange={e=>setBank({...bank,accountHolderName:e.target.value})}/><button disabled={saving}>Add bank account</button></form><table><thead><tr><th>Employee</th><th>Bank</th><th>Account</th><th>IBAN</th><th>Status</th></tr></thead><tbody>{accounts.map(x=><tr key={x._id}><td>{x.employee?.name||x.employeeId}</td><td>{x.bankName}</td><td>{x.accountNumber}</td><td>{x.iban||'-'}</td><td>{x.status}</td></tr>)}</tbody></table></section>}
  </div>;
}
