import { useEffect, useState } from 'react';
import API from '../../services/api';

const emptyContract = { employeeId:'', contractNumber:'', startDate:'', endDate:'', basicSalary:0, status:'Active' };
const emptyBank = { employeeId:'', bankName:'', branchName:'', accountName:'', accountNumber:'', iban:'', swiftCode:'', disbursementMethod:'BankAccount', preferredGateway:'Fawry' };

export default function HrmExtensionsPage() {
  const [tab, setTab] = useState('contracts'); const [contracts, setContracts] = useState([]); const [accounts, setAccounts] = useState([]); const [employees, setEmployees] = useState([]);
  const [contract, setContract] = useState(emptyContract); const [bank, setBank] = useState(emptyBank); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const [c,e] = await Promise.all([API.get('/hrm/contracts'), API.get('/hrm/employees')]); setContracts(c.data.data||[]); setEmployees(e.data.data||[]); const bankResults = await Promise.all((e.data.data||[]).map(async employee => { try { const r=await API.get(`/hrm/bank-account/${employee._id}`); return r.data.data ? {...r.data.data, employee} : null; } catch { return null; } })); setAccounts(bankResults.filter(Boolean)); } catch(e){ setError(e.response?.data?.message||'Failed to load HRM extensions'); } finally { setLoading(false); } };
  useEffect(()=>{load();},[]);
  const saveContract = async event => { event.preventDefault(); setSaving(true); setError(''); try { await API.post('/hrm/contracts', contract); setContract(emptyContract); await load(); } catch(e){ setError(e.response?.data?.message||'Failed to create contract'); } finally { setSaving(false); } };
  const saveBank = async event => { event.preventDefault(); setSaving(true); setError(''); try { await API.put(`/hrm/bank-account/${bank.employeeId}`, bank); setBank(emptyBank); await load(); } catch(e){ setError(e.response?.data?.message||'Failed to save bank account'); } finally { setSaving(false); } };
  if(loading) return <div className="loading-state">Loading HRM extensions…</div>;
  return <div className="page-container"><div className="page-header"><div><h1>HRM Extensions</h1><p>Contracts and employee banking integrated with the HRM backend.</p></div></div>{error&&<div className="alert alert-error">{error}</div>}<div className="tabs" style={{display:'flex',gap:8,margin:'20px 0'}}><button onClick={()=>setTab('contracts')} className={tab==='contracts'?'active':''}>Contracts</button><button onClick={()=>setTab('banking')} className={tab==='banking'?'active':''}>Employee Banking</button></div>
  {tab==='contracts'&&<section className="card"><h2>Employee Contracts</h2><form onSubmit={saveContract} style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><select value={contract.employeeId} onChange={e=>setContract({...contract,employeeId:e.target.value})} required><option value="">Select employee</option>{employees.map(x=><option key={x._id} value={x._id}>{x.name||x.fullName||x.employeeNumber||x._id}</option>)}</select><input placeholder="Contract number" value={contract.contractNumber} onChange={e=>setContract({...contract,contractNumber:e.target.value})} required/><input type="date" value={contract.startDate} onChange={e=>setContract({...contract,startDate:e.target.value})} required/><input type="date" value={contract.endDate} onChange={e=>setContract({...contract,endDate:e.target.value})}/><input type="number" min="0" placeholder="Basic salary" value={contract.basicSalary} onChange={e=>setContract({...contract,basicSalary:e.target.value})}/><button disabled={saving}>Create contract</button></form><table><thead><tr><th>Contract</th><th>Employee</th><th>Start</th><th>Salary</th><th>Status</th></tr></thead><tbody>{contracts.map(x=><tr key={x._id}><td>{x.contractNumber}</td><td>{x.employee?.name||x.employeeId}</td><td>{x.startDate?.slice(0,10)}</td><td>{x.basicSalary}</td><td>{x.status}</td></tr>)}</tbody></table></section>}
  {tab==='banking'&&<section className="card"><h2>Employee Bank Accounts</h2><form onSubmit={saveBank} style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10}}><select value={bank.employeeId} onChange={e=>setBank({...bank,employeeId:e.target.value})} required><option value="">Select employee</option>{employees.map(x=><option key={x._id} value={x._id}>{x.name||x.fullName||x.employeeNumber||x._id}</option>)}</select><input placeholder="Bank name" value={bank.bankName} onChange={e=>setBank({...bank,bankName:e.target.value})} required/><input placeholder="Branch" value={bank.branchName} onChange={e=>setBank({...bank,branchName:e.target.value})}/><input placeholder="Account name" value={bank.accountName} onChange={e=>setBank({...bank,accountName:e.target.value})} required/><input placeholder="Account number" value={bank.accountNumber} onChange={e=>setBank({...bank,accountNumber:e.target.value})}/><input placeholder="IBAN" value={bank.iban} onChange={e=>setBank({...bank,iban:e.target.value})}/><input placeholder="SWIFT code" value={bank.swiftCode} onChange={e=>setBank({...bank,swiftCode:e.target.value})}/><select value={bank.disbursementMethod} onChange={e=>setBank({...bank,disbursementMethod:e.target.value})}><option>BankAccount</option><option>FawryWallet</option><option>PayMobWallet</option></select><select value={bank.preferredGateway} onChange={e=>setBank({...bank,preferredGateway:e.target.value})}><option>Fawry</option><option>PayMob</option><option>InstaPay</option><option>BankAPI</option><option>Amazon</option></select><button disabled={saving}>Save bank account</button></form><table><thead><tr><th>Employee</th><th>Bank</th><th>Account</th><th>IBAN</th><th>Verified</th></tr></thead><tbody>{accounts.map(x=><tr key={x._id}><td>{x.employee?.name||x.employee?.fullName||x.employeeId}</td><td>{x.bankName}</td><td>{x.accountNumber||'-'}</td><td>{x.iban||'-'}</td><td>{x.isVerified?'Yes':'No'}</td></tr>)}</tbody></table></section>}
  </div>;
}
